name: Bug PR
description: Crate a pull request for bugs
title: "[Bug]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fix this bug!
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority for the implementation of this new feature
      options:
        - Fire
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: caveats
    attributes:
      label: Caveats
      description: Describe anything else that should be considered or has to take a further look regarding this feature
      render: shell
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Before merging this PR, I (the assignee), ensure that these requirements have been fulfilled if necessary.
        - label: I have created unit tests for the most important changes implemented (appart from passing Sonarqube requirements)
          required: true
        - label: I have created adequate cluster tests and they work succesfully
          required: true
        - lalel: I have added the **dev-development** label and the code builds and deploys to **dev** succesfully
          required: true
        - label: I have crated/modified necessary infrastructure resources in terraform
        - label: I have updated the wiki or documented if necessary
  - type: textarea
    id: caveats
    attributes:
      label: Caveats
      description: Describe anything else that should be considered or has to take a further look regarding this feature
      render: shell

